### ISSUE TITLE
Add support for beyond1lte (codename wrongly reported as beyond1)

### ISSUE THREAD

**Issue by marmotte32** [openandroidinstaller-dev/openandroidinstaller#229] opened 2023-08-02 23:31 UTC
**Device name**
Samsung Galaxy S10
codename: beyond1lte
model: SM-G973F/DS

**Device images**
Original Stock Samsung ROM installed is Android 12:
AP/PDA: G973FXXSGHWC1   (PDA)
CSC:        G973FOXJGHVJ4
CP:          G973FXXSGHWB3   (BaseBand)

Target: /e/OS S 1.13: e-1.13-s-20230726314102-dev-beyond1lte.zip
https://images.ecloud.global/dev/beyond1lte/

**Do you own the device and would be willing to test the installer?**
I own the device but this will be my main device so I will install it manually following this documentation:
https://doc.e.foundation/devices/beyond1lte/install

**Additional context**
I will post a screenshot of the error message later.
Don't get me wrong, I like your approach but there is obviously something wrong with your tool for S10 beyond1lte

The error you tool shown is:
"Device with code 'beyond1' is not supported yet."

So somehow, the tool is getting the wrong codename for S10.

if I run a simple adb shell
it show me:
beyond1:/ $

So maybe your tool use the same to state that I have a beyond1 when in fact it is a beyond1lte ?

Here is an output of the adb command:    `getprop | grep beyond1`
```
[ro.bootimage.build.fingerprint]: [samsung/beyond1ltexx/beyond1:12/SP1A.210812.016/G973FXXSGHWC1:user/test-keys]
[ro.build.description]: [beyond1ltexx-user 12 SP1A.210812.016 G973FXXSGHWC1 release-keys]
[ro.build.fingerprint]: [samsung/beyond1lteeea/beyond1:12/SP1A.210812.016/G973FXXSGHWC1:user/release-keys]
[ro.build.flavor]: [beyond1ltexx-user]
[ro.build.product]: [beyond1lte]
[ro.build.version.base_os]: [samsung/beyond1lteeea/beyond1:12/SP1A.210812.016/G973FXXUGHVJ5:user/release-keys]
[ro.odm.build.fingerprint]: [samsung/beyond1ltexx/beyond1:12/SP1A.210812.016/G973FXXSGHWC1:user/release-keys]
[ro.product.bootimage.device]: [beyond1]
[ro.product.bootimage.name]: [beyond1ltexx]
[ro.product.device]: [beyond1]
[ro.product.name]: [beyond1lteeea]
[ro.product.odm.device]: [beyond1]
[ro.product.odm.name]: [beyond1ltexx]
[ro.product.system.device]: [beyond1]
[ro.product.system.name]: [beyond1ltexx]
[ro.product.system_ext.device]: [beyond1]
[ro.product.system_ext.name]: [beyond1ltexx]
[ro.product.vendor.device]: [beyond1]
[ro.product.vendor.name]: [beyond1ltexx]
[ro.product.vendor_dlkm.device]: [beyond1]
[ro.product.vendor_dlkm.name]: [beyond1ltexx]
[ro.system.build.fingerprint]: [samsung/beyond1ltexx/beyond1:12/SP1A.210812.016/G973FXXSGHWC1:user/release-keys]
[ro.system_ext.build.fingerprint]: [samsung/beyond1ltexx/beyond1:12/SP1A.210812.016/G973FXXSGHWC1:user/release-keys]
[ro.vendor.build.fingerprint]: [samsung/beyond1ltexx/beyond1:12/SP1A.210812.016/G973FXXSGHWC1:user/release-keys]
[ro.vendor_dlkm.build.fingerprint]: [samsung/beyond1ltexx/beyond1:12/SP1A.210812.016/G973FXXSGHWC1:user/release-keys]
```

**Comment by marmotte32** [comment] 2023-08-02 23:33
Here is the screenshot:
![2023-08-03_01-31](https://github.com/openandroidinstaller-dev/openandroidinstaller/assets/4152464/25e0f151-1417-4533-9f3d-9e5b09162fd0)

**Comment by marmotte32** [comment] 2023-08-02 23:47
just to mention that this command shown the right codename:
`adb shell getprop | grep ro.build.product`
**[ro.build.product]: [beyond1lte]**

**Comment by MagicLike** [comment] 2023-08-03 09:49
Thank you for this very detailed report - this is actually about to be fixed in #205!
If this urgent for you and you can't wait for the next release, I can show you how to apply the patch locally / try to build a version for you.

**Comment by marmotte32** [comment] 2023-08-03 11:09
Thank you for you quick answer and for having a look into this issue @MagicLike !

If I understand well the workaround for me would be to apply only this modification?
https://github.com/openandroidinstaller-dev/openandroidinstaller/pull/205/commits/1148287df7c1199c1c66974717a820077d30d5d9
Like just edit the "openandroidinstaller/assets/configs/beyond1lte.yaml" file and add "  - beyond1"?


If this is the patch, I have an additional question, are you sure it is safe to do that?
For me it is ok, I know what I'm doing but there are 2 variants of the normal S10 beyond1xxx:
- the one with a Snapdragon (beyond1qlte) SoC 
- and the one with an  Exynos (beyond1lte)

Problem is that /e/OS and LOS are only compatible with S10 Exynos (aka beyond1lte) and not with the Snapdragon (beyond1qlte)
So what happen if a beginner flash /e/OS on a Snapdragon due to bad codename beyond1, it could brick the phone?

**Comment by MagicLike** [comment] 2023-08-03 11:23
> Thank you for you quick answer and for having a look into this issue @MagicLike !
> 
> If I understand well the workaround for me would be to apply only this modification? [1148287](https://github.com/openandroidinstaller-dev/openandroidinstaller/commit/1148287df7c1199c1c66974717a820077d30d5d9) Like just edit the "openandroidinstaller/assets/configs/beyond1lte.yaml" file and add " - beyond1"?

Pretty much yeah! - you would need to clone my branch onto your pc and run it out of the terminal. But you can also wait a sec and I can let GitHub Actions compile a version for you!

> If this is the patch, I have an additional question, are you sure it is safe to do that? For me it is ok, I know what I'm doing but there are 2 variants of the normal S10 beyond1xxx:
> 
>     * the one with a Snapdragon (beyond1qlte) SoC
> 
>     * and the one with an  Exynos (beyond1lte)
> 
> 
> Problem is that /e/OS and LOS are only compatible with S10 Exynos (aka beyond1lte) and not with the Snapdragon (beyond1qlte) So what happen if a beginner flash /e/OS on a Snapdragon due to bad codename beyond1, it could brick the phone? https://doc.e.foundation/devices/beyond1lte

Interesting question - I don't actually know. I have read that incompatible roms can brick the phone, but before that you would need to have a compatible recovery, which would not boot if it was the wrong SoC. But yeah theoretically it would be possible - therefore there are multiple warnings everywhere that flashing potentially could brick the phones. Also I think the `beyond1ylte` always has the `q` after the `1` - regardless of the `lte`, so it should not be a problem at all!

**Comment by marmotte32** [comment] 2023-08-03 20:44
Thank you it works, you can close this issue !
But again I'm not sure it is really safe this patch as it is somehow bypassing the real name of the phone.

![image](https://github.com/openandroidinstaller-dev/openandroidinstaller/assets/4152464/be952518-d3f7-4c33-bf59-5d8eda77b0a9)


PS: There is another issue in the tool, it does reboot in download mode instead of bootloader unlock mode.
I've open a new issue here: https://github.com/openandroidinstaller-dev/openandroidinstaller/issues/231

**Comment by MagicLike** [comment] 2023-08-03 21:13
> Thank you it works, you can close this issue ! But again I'm not sure it is really safe this patch as it is somehow bypassing the real name of the phone.

Great to hear, but you will have to close the issue yourself, as I don't have any write rights in this repo... Also it is not "bypassing" the name of the phone, but rather adapting to the different names, which exist in multiple devices. (That is totally normal)

> PS: There is another issue in the tool, it does reboot in download mode instead of bootloader unlock mode. I've open a new issue here: #231

Afaik, this is totally by design - the text might be a bit misleading. Via the download mode the recovery gets completely wiped by flashing twrp as the new one. (Different to all other devices, which just boot twrp and keep the original recovery for compatibility and legacy support)

**Closed** 2023-08-04 06:14 UTC
Labels: device
