### ISSUE TITLE
Add support for `gtaxlwifi`

### ISSUE THREAD

**Issue by hechendorf** [openandroidinstaller-dev/openandroidinstaller#465] opened 2024-02-26 19:36 UTC
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

Samsung

### Name

Galaxy Tab A

### Device code

gtaxlwifi

### Model

SM-T580

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by tsterbak** [comment] 2024-03-24 11:19
It should be possible to support this device:

    TWRP: https://twrp.me/samsung/samsunggalaxytaba101wifi2016.html
    LineageOS: unclear

You can create a config file for your device and contribute it to the project: https://github.com/openandroidinstaller-dev/openandroidinstaller/blob/main/docs/how_to_contribute_your_own_installation_configurations.md
Easiest is to start off an existing config file :)

Let me know if you need any help.

**Comment by tsterbak** [comment] 2024-03-24 12:13
duplicate of #349

**Closed** 2024-03-27 17:39 UTC
Labels: duplicate, device
