### ISSUE TITLE
Make Rom & recovery install optional

### ISSUE THREAD

**Issue by freechelmi** [openandroidinstaller-dev/openandroidinstaller#88] opened 2023-02-24 12:10 UTC
For a first install recovery is compulsory , but it could be useful to disable recovery flash for further installs

**Comment by tsterbak** [comment] 2023-02-24 14:49
Good point :)

Flashing the recovery only happens for Samsung devices, since heimdall doesn't seem to only allow to boot into recovery (and Samsung didn't build any A/B-partitioned devices, so far). All other devices only boot TWRP, so it is necessary to do this step every time.
I wanted to keep the options a user has as low as possible (within some boundaries of functionality). So do you think this would be mostly a convenience feature (to not flash the recovery every time), or could it prevent some issues?

**Comment by freechelmi** [comment] 2023-02-24 14:55
I agree we need to present the least options to the user possibly for greater success

I guess we could image an "advanced mode" that would : 

- show the logs automatically 
- enable to flash only either recovery or system 
- do some other dangerous stuff

I plan on using OAI for "batch flashing" the phones we refurb

**Comment by tsterbak** [comment] 2023-02-24 18:20
The advanced or extended mode idea sounds like a reasonable plan forward. I'll put it on the roadmap/backlog.
I need to fix and improve some other things and do some clean-ups before extending the codebase in this direction.

What devices are you planning to flash? Are those a lot of different devices or mostly the same ones? That would definitely great if it helps you and at the same time provides some regular feedback about potential regressions or so.

**Comment by tsterbak** [comment] 2023-04-19 18:35
@freechelmi I'm planning to move this forward now. I'm just thinking about how users should be able to enter the "advanced mode".

Options I'm thinking about right now:
- a command line flag to add when you start the executable from the terminal
- a toggle switch or checkbox on the first view

What do you think?

**Comment by tsterbak** [comment] 2023-10-07 08:42
Resolved with #141

**Closed by tsterbak** 2023-10-07 08:42 UTC
Labels: enhancement, help wanted
